booth/urls.py
from django.urls import path

from . import views

app_name = 'booth'
urlpatterns = [
    path('', views.index, name='index'),
]

bulletin/urls.py
from django.urls import path

from . import views

app_name = 'bulletin'
urlpatterns = [
    path('', views.check, name='check'),
]

register/urls.py
from django.urls import path

from . import views

app_name = 'register'
urlpatterns = [
    path('', views.create, name='create'),
]

resist/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('booth.urls')),
    path('bulletin/', include('bulletin.urls')),
    path('register/', include('register.urls')),
    path('supervisor/', include('supervisor.urls')),
    #path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

booth/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone


# Create your views here.
def index(request):
    return render(request, 'booth/index.html', {})
    #context_object_name  = ''

booth/templates/booth/base.html
{% load static %}

<!DOCTYPE html>
<head>
  <title>{{title}}</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="min-width=768, max-width:1024, max-height=1000, initial-scale=1, user-scalable=0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width">
  <link rel="apple-touch-icon-precomposed" href="{% static 'booth/style.css' %}" />
  <link rel="stylesheet" href="{% static 'booth/style.css' %}" type="text/css" media="screen" />
  {% block stylesheets %}
  {% endblock %}
  {% block scripts %}
  {% endblock %} 
</head>
<body
  {% if request.user_agent.is_mobile %}
    class="mobile"
  {% endif %}
  ontouchstart=""
>
  <section id="header">
  	<header class="container">
  		<input id="button-settings" type="button" class="button icon settings open-settings" value="Settings" />
  		<input id="button-help" type="button" class="button icon help open-help" value="Help" />
  		<input id="button-review" type="button" class="button review" value="Review" />
  	</header>
  </section>


  <section id="page">
  	<article class="container">
  		{% block content %}
      {% endblock %}
  	</article>
  </section>

  <section id="footer">
  	<footer class="container">
  		<input id="button-back" type="button" class="button icon back" value="Back"/>
  		<input id="button-cancel" type="button" class="button icon cancel" value="Cancel" />
  		<input id="button-skip" type="button" class="button icon skip" value="Skip" />
      <!--
      <div id="progress">
  			<p><strong><span id="progress-current"><?php echo ballot_current_race(); ?></span></strong> of <strong><span id="progress-total"><?php echo ballot_total_races(); ?></span></strong></p>
  		</div>
      -->
  		<input id="button-next" type="button" class="button icon next green" value="Next" />
  		<input id="button-accept" type="button" class="button icon accept green" value="Accept" />
  		<input id="button-cast" type="button" class="button cast green" value="Cast your vote" />
  		<input id="button-return-review" type="button" class="button icon return green" value="Return to review and cast your vote" />
  	</footer>
  </section>
</body>

booth/templates/booth/booth_base.html
{% load static %}

<!DOCTYPE html>
<head>
  <title>{{title}}</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="min-width=768, max-width:1024, max-height=1000, initial-scale=1, user-scalable=0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width">
  <link rel="apple-touch-icon-precomposed" href="{% static 'booth/style.css' %}" />
  <link rel="stylesheet" href="{% static 'booth/style.css' %}" type="text/css" media="screen" />
</head>
<body
    {% if request.user_agent.is_mobile %}
      class="mobile"
    {% endif %}
    ontouchstart=""
  >
  <section id="header">
  	<header class="container">
  		<input id="button-settings" type="button" class="button icon settings open-settings" value="Settings" />
  		<input id="button-help" type="button" class="button icon help open-help" value="Help" />
  		<input id="button-review" type="button" class="button review" value="Review" />
  	</header>
  </section>


  <section id="page">
  	<article class="container">
  		<div id="description">
  			<h1><strong>Resist</strong></h1>
  			<aside>
  				Template's ready.
  			</aside>
  		</div>
  	</article>
  </section>

  <section id="footer">
  	<footer class="container">
  		<input id="button-back" type="button" class="button icon back" value="Back" />
  		<input id="button-cancel" type="button" class="button icon cancel" value="Cancel" />
  		<input id="button-skip" type="button" class="button icon skip" value="Skip" />
      <!--
      <div id="progress">
  			<p><strong><span id="progress-current"><?php echo ballot_current_race(); ?></span></strong> of <strong><span id="progress-total"><?php echo ballot_total_races(); ?></span></strong></p>
  		</div>
      -->
  		<input id="button-next" type="button" class="button icon next green" value="Next" />
  		<input id="button-accept" type="button" class="button icon accept green" value="Accept" />
  		<input id="button-cast" type="button" class="button cast green" value="Cast your vote" />
  		<input id="button-return-review" type="button" class="button icon return green" value="Return to review and cast your vote" />
  	</footer>
  </section>

booth/templates/booth/index.html
{% extends 'booth/base.html' %}

{% block content %}

  <div id="description">
    <h1><strong>Resist</strong></h1>
      <p>What do you want to do?</p>

          <a href="{% url 'bulletin:check' %}">
          <div class = "description">
            <input id="button-bulletin" type="button" class="button" value="Check a Bulletin Board" />
          </div>
          </a>
          <a href="{% url 'register:create' %}">
          <div class= "description">
            <input id="button-register" type="button" class="button" value="Register for an Election" />
          </div>
          </a>
          <a href="#">
          <div class = "description">
            <input id="button-ballot" type="button" class="button" value="Cast a Vote" />
          </div>
          </a>
    </div>

{% endblock %}