booth/urls.py
from django.urls import path

from . import views

app_name = 'booth'
urlpatterns = [
    path('', views.index, name='index'),
]

resist/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('booth.urls')),
    path('bulletin/', include('bulletin.urls')),
    path('register/', include('register.urls')),
    path('supervisor/', include('supervisor.urls')),
    #path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

supervisor/urls.py
from django.urls import path

from . import views

app_name = 'supervisor'
urlpatterns = [
    #supervisor urls
    path('createelection/', views.createelection, name='createelection'),
    path('addelection/', views.addelection, name='addelection'),
    path('createtabulation/', views.createtabulation, name='createtabulation'),
    path('createauth/', views.createvoter, name='createvoter'),
    path('createvoter/', views.createvoter, name='createvoter'),
    path('regvoter/', views.regvoter, name='register'),
]

supervisor/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from bulletin.models import Election, Voter
# Create your views here.


def createelection(request):
    return render(request, 'supervisor/createelection.html', {})

def addelection(request):
    election = Election()
    election.name = request.POST['election_name']
    election.organization = request.POST['election_organization']
    election.description = request.POST['election_description']
    election.help_email = request.POST['email']
    #TODO: Change the following to call key generators
    election.public_key = "Filler Public Key"
    election.private_key = "Filler Private Key"
    election.save();
    #TODO: change the redirect URL
    return HttpResponseRedirect(reverse('supervisor:createelection'))

def createvoter(request):
    pass

def createtabulation(request):
    pass

def createauth(request):
    pass

def regvoter(request):
    pass

supervisor/templates/supervisor/base.html
{% load static %}

<!DOCTYPE html>
<head>
  <title>{{title}}</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="min-width=768, max-width:1024, max-height=1000, initial-scale=1, user-scalable=0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width">
  <link rel="apple-touch-icon-precomposed" href="{% static 'supervisor/style.css' %}" />
  <link rel="stylesheet" href="{% static 'supervisor/style.css' %}" type="text/css" media="screen" />
</head>
<body
  {% if request.user_agent.is_mobile %}
    class="mobile"
  {% endif %}
  ontouchstart=""
>
  <section id="header">
  	<header class="container">
  		<input id="button-settings" type="button" class="button icon settings open-settings" value="Settings" />
  		<input id="button-help" type="button" class="button icon help open-help" value="Help" />
  		<input id="button-review" type="button" class="button review" value="Review" />
  	</header>
  </section>


  <section id="page">
  	<article class="container">
  		{% block content %}
      {% endblock %}
  	</article>
  </section>

  <section id="footer">
  	<footer class="container">
  		<input id="button-back" type="button" class="button icon back" value="Back"/>
  		<input id="button-cancel" type="button" class="button icon cancel" value="Cancel" />
  		<input id="button-skip" type="button" class="button icon skip" value="Skip" />
      <!--
      <div id="progress">
  			<p><strong><span id="progress-current"><?php echo ballot_current_race(); ?></span></strong> of <strong><span id="progress-total"><?php echo ballot_total_races(); ?></span></strong></p>
  		</div>
      -->
      {% block footer %}
      {% endblock %}
  		<input id="button-next" type="button" class="button icon next green" value="Next" />
  		<input id="button-accept" type="button" class="button icon accept green" value="Accept" />
  		<input id="button-cast" type="button" class="button cast green" value="Cast your vote" />
  		<input id="button-return-review" type="button" class="button icon return green" value="Return to review and cast your vote" />
  	</footer>
  </section>
</body>

supervisor/templates/supervisor/createelection.html
{% extends 'supervisor/base.html' %}

{% block content %}

    <div id="description">
      <h1><strong>Create Election</strong></h1>
        <aside>
          <form action="{% url 'supervisor:addelection' %}" method="post">
            {% csrf_token %}
            <div class="option">
              <label for="election_name">Election Name: </label>
                <input name="election_name" type="text">
            </div>
            <div class="option">
              <label for="election_organization">Organization: </label>
                <input name="election_organization" type="text">
            </div>
            <div class="option">
              <label for="election_description">Description: </label>
                <input name="election_description" type="text">
            </div>
            <div class="option">
              <label for="email">Enter email for election support:</label>
                <input type="email" name="email" id="email" required>
            </div>
        </aside>
    </div>
{% endblock %}

{% block footer %}
    <button id="button-cast" type="sumbit" class="onscreen button cast green" value="Create Election">Create Election</button>
{% endblock %}